---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: corpweb-deploy
  labels: 
    app: corpweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: corpweb
  template:
    metadata:
      labels:
        app: corpweb
    spec:
      containers:
      - name: websvr
        image: nginx
        ports:
          - name: http
            containerPort: 80
        volumeMounts:
            # name must match the volume name below
            - name: appvol
              mountPath: "/usr/share/nginx/html"
      volumes:
      - name: appvol
        persistentVolumeClaim:
          claimName: app-pvc-claim
---
#Service
apiVersion: v1
kind: Service
metadata:
  name: corpweb-svc
#  namespace: corp-lab
  labels:
    app: corpweb
spec:
  ports:
  - port: 80
    # targetPort: 8080
  selector:
    app: corpweb  
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: corpweb-ing
  #namespace: corp-lab
  labels:
    app: corpweb
spec:
  rules:
  - host: corpweb.k8s01-app.lab.local
    http:
      paths:
      - backend:
          serviceName: corpweb-svc
          servicePort: 80